(load "utils.scm")
(load "chapter1/code.scm")
(logoprint "Chapter 2 | rationals")
(load "chapter2/rational.scm")
(logoprint "Chapter 2 | segments")
(load "chapter2/segments.scm")
(logoprint "Chapter 2 | rects")
(load "chapter2/rects.scm")
(logoprint "Chapter 2 | powers")
(load "chapter2/powers.scm")
(logoprint "Chapter 2 | intervals")
(load "chapter2/intervals.scm")
(logoprint "Chapter 2 | lists")
(load "chapter2/lists.scm")
(logoprint "Chapter 2 | trees")
(load "chapter2/trees.scm")



(loading-chapter 2)
