(load "chapter1/code.scm")
(load "chapter2/rational.scm")
(load "chapter2/segments.scm")
(load "chapter2/rects.scm")
(load "chapter2/powers.scm")
(load "chapter2/intervals.scm")

(define (main)
  (newline)
  (display "-----------------------------")
  (newline)  
  (display "Chapter loading successfull.")
  (newline)
  (display "-----------------------------")
  0)
(main)
